### ISSUE TITLE
编译python-inject这个二进制不能通过额？

### ISSUE THREAD

**Issue by pandaluocheng** [Hackerl/python-inject#2]
在编译的时候提示:zero-src提示undefined reference to `Catch::StringMaker<std::byte, void>::convert(std::byte)'；
对于python注入必须用python-inject？我用pangolin注入报catch exit syscall: -1

**Comment by Hackerl** [comment]
python-inject 有潜在问题，注入请使用 python-loader。

**Comment by Hackerl** [comment]
python-loader 注入问题我们在 Elkeid issue 里面讨论。
